name: pipeline

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    needs: code-analisys
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml      
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: target/
   
    - name: Upload JAR
        #This uploads artifacts from your workflow allowing you to share data between jobs and store data once a workflow is complete.
      uses: actions/upload-artifact@v4.4.0
      with:
        #Set artifact name
        name: artifact
        #From this path
        path: ./target/demo-0.0.2.7-SNAPSHOT.jar
    
    - name: Package
      run: mvn package  
      
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     contents: read
  #     packages: write
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v3
  #       with:
  #         java-version: '11'
  #         distribution: 'adopt'
  #         package: '*.jar'
  #     - name: Publish package
  #       run: mvn --batch-mode deploy
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
  
  deploy-azure:
    needs: build  
    name: Deploy-azure
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'    
    environment:
      name: AZURE-PRO        
    steps:
       - name: Download JAR
         uses: actions/download-artifact@v4
         with:
            path: target/  
       - name: Display structure of downloaded files
         run: ls -R
       - name: DeployAzure   
         uses: azure/webapps-deploy@v2.2.13
         with:
            app-name: DevopsFiap-On-app
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} 
            package: '${{ github.workspace }}/target/artifact/*.jar'
            clean: false
